"""add soft delete to games table

Revision ID: 0643cad4739b
Revises: 0d8cb6d699e0
Create Date: 2025-07-03 18:29:43.942960

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0643cad4739b"
down_revision: str | Sequence[str] | None = "0d8cb6d699e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_games_deleted_at"), "games", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_games_deleted_at"), table_name="games")
    op.drop_column("games", "deleted_at")
    # ### end Alembic commands ###
