"""Initial schema

Revision ID: 0d8cb6d699e0
Revises:
Create Date: 2025-07-03 17:52:30.754789

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d8cb6d699e0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "FAILED", "PAUSED", name="gamestatus"),
            nullable=False,
        ),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("current_turn", sa.Integer(), nullable=False),
        sa.Column("final_outcome", sa.JSON(), nullable=True),
        sa.Column("game_metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_status"), "games", ["status"], unique=False)
    op.create_table(
        "actions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("player_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "NOMINATE",
                "VOTE_TEAM",
                "CALL_EMERGENCY_SAFETY",
                "VOTE_EMERGENCY",
                "DISCARD_PAPER",
                "DECLARE_VETO",
                "RESPOND_VETO",
                "PUBLISH_PAPER",
                "USE_POWER",
                "SEND_CHAT_MESSAGE",
                "OBSERVE",
                name="actiontype",
            ),
            nullable=False,
        ),
        sa.Column("action_data", sa.JSON(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actions_game_id"), "actions", ["game_id"], unique=False)
    op.create_index(
        op.f("ix_actions_turn_number"), "actions", ["turn_number"], unique=False
    )
    op.create_table(
        "adk_sessions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("app_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("player_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("session_state", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_update_time", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_adk_sessions_app_name"), "adk_sessions", ["app_name"], unique=False
    )
    op.create_index(
        op.f("ix_adk_sessions_user_id"), "adk_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "agent_metrics",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("player_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("invalid_attempts", sa.Integer(), nullable=False),
        sa.Column("internal_state_size", sa.Integer(), nullable=True),
        sa.Column("memory_usage_mb", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_metrics_game_id"), "agent_metrics", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_metrics_player_id"), "agent_metrics", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_metrics_turn_number"),
        "agent_metrics",
        ["turn_number"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("speaker_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_game_id"), "chat_messages", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_turn_number"),
        "chat_messages",
        ["turn_number"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "ACTION_ATTEMPTED",
                "STATE_CHANGED",
                "CHAT_MESSAGE",
                "PHASE_TRANSITION",
                "GAME_ENDED",
                "POWER_TRIGGERED",
                "PAPER_PUBLISHED",
                "VOTE_COMPLETED",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column("player_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_game_id"), "events", ["game_id"], unique=False)
    op.create_index(
        op.f("ix_events_turn_number"), "events", ["turn_number"], unique=False
    )
    op.create_table(
        "game_states",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("state_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("checksum", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_states_game_id"), "game_states", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_game_states_turn_number"), "game_states", ["turn_number"], unique=False
    )
    op.create_table(
        "players",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("player_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_config", sa.JSON(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("SAFETY", "ACCELERATIONIST", "AGI", name="role"),
            nullable=False,
        ),
        sa.Column(
            "allegiance",
            sa.Enum("SAFETY", "ACCELERATION", name="allegiance"),
            nullable=False,
        ),
        sa.Column("alive", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_game_id"), "players", ["game_id"], unique=False)
    op.create_table(
        "adk_events",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["adk_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_adk_events_sequence_number"),
        "adk_events",
        ["sequence_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_adk_events_session_id"), "adk_events", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adk_events_session_id"), table_name="adk_events")
    op.drop_index(op.f("ix_adk_events_sequence_number"), table_name="adk_events")
    op.drop_table("adk_events")
    op.drop_index(op.f("ix_players_game_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_game_states_turn_number"), table_name="game_states")
    op.drop_index(op.f("ix_game_states_game_id"), table_name="game_states")
    op.drop_table("game_states")
    op.drop_index(op.f("ix_events_turn_number"), table_name="events")
    op.drop_index(op.f("ix_events_game_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_chat_messages_turn_number"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_game_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_agent_metrics_turn_number"), table_name="agent_metrics")
    op.drop_index(op.f("ix_agent_metrics_player_id"), table_name="agent_metrics")
    op.drop_index(op.f("ix_agent_metrics_game_id"), table_name="agent_metrics")
    op.drop_table("agent_metrics")
    op.drop_index(op.f("ix_adk_sessions_user_id"), table_name="adk_sessions")
    op.drop_index(op.f("ix_adk_sessions_app_name"), table_name="adk_sessions")
    op.drop_table("adk_sessions")
    op.drop_index(op.f("ix_actions_turn_number"), table_name="actions")
    op.drop_index(op.f("ix_actions_game_id"), table_name="actions")
    op.drop_table("actions")
    op.drop_index(op.f("ix_games_status"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
